// 게시글 생성
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "첫 번째 게시글",
  "content": "안녕하세요! Go로 만든 첫 게시글입니다.",
  "author": "홍길동"
}
###
//게시글 목록 조회
GET http://localhost:8080/api/v1/posts

###
//게시글 상세 조회
GET http://localhost:8080/api/v1/posts/1

###
// 게시글 수정
PUT http://localhost:8080/api/v1/posts/1
Content-Type: application/json

{
  "title": "수정된 제목",
  "content": "수정된 내용입니다."
}

###
// 게시글 삭제
DELETE http://localhost:8080/api/v1/posts/1

###

// 없는 게시글 조회
GET http://localhost:8080/api/v1/posts/999

###